<?php

namespace PathfinderBundle\Repository;

/**
 * Class_FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Class_FeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
