<?php

namespace PathfinderBundle\Repository;

/**
 * FeatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatRepository extends \Doctrine\ORM\EntityRepository
{
}
