<?php

namespace PathfinderBundle\Repository;

/**
 * Race_FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Race_FeatureRepository extends \Doctrine\ORM\EntityRepository
{
}
